---
- hosts: webservers
  become: yes
  tasks:
    - name: INSTALL APACHE2
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: ENABLE MOD_REWRITE
      apache2_module:
        name: rewrite
        state: present
      notify:
        - RESTART APACHE2

    - name: APACHE2 Listen on port 8088
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8088" state=present
      notify:
        - RESTART APACHE2

    - name: Create dirs
      command: mkdir -p /var/www/html/static
      notify:
        - RESTART APACHE2

    - name: Home Page
      copy:
        src: templates/index.html
        dest: /var/www/html/index.html
      notify:
        - RESTART APACHE2

    - name: Stylesheet
      copy:
        src: static/style.css
        dest: /var/www/html/static/style.css
      notify:
        - RESTART APACHE2

  handlers:
    - name: RESTART APACHE2 wrong (systemd not active)
      service: name=apache2 state=restarted

    - name: RESTART APACHE2
      ansible.builtin.sysvinit:
        name: apache2
        state: restarted
